services:
  - type: web
    name: jarvis-flask-app
    env: python
    plan: free
    buildCommand: |
      echo "Installing Flask dependencies..."
      pip install -r requirements.txt
      echo "Build complete!"
    startCommand: |
      echo "Starting Flask app with WSGI..."
      python wsgi.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: OPENROUTER_API_KEY
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: SLACK_BOT_TOKEN
        sync: false
      - key: SLACK_CHANNEL_ID
        sync: false
      - key: AI_MODEL
        value: anthropic/claude-3-sonnet 